// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbContext.Migrations.SqlServerDbContext
{
    [DbContext(typeof(MainDbContext.SqlServerDbContext))]
    [Migration("20261001132248_miInitial")]
    partial class miInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbModels.AddressDbM", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostalCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(200)");

                    b.HasKey("AddressId");

                    b.HasIndex("PostalCodeId");

                    b.ToTable("Address", "supusr", t =>
                        {
                            t.HasCheckConstraint("CK_StreetNameNotEmpty", "LEN(TRIM(StreetName)) > 0");
                        });
                });

            modelBuilder.Entity("DbModels.AttractionCategoryDbM", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("AttractionId", "CategoryId");

                    b.HasIndex("AttractionId", "CategoryId");

                    b.HasIndex("CategoryId", "AttractionId");

                    b.ToTable("AttractionCategory", "supusr");
                });

            modelBuilder.Entity("DbModels.AttractionDbM", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttractionDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AttractionName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("AttractionId");

                    b.HasIndex("AddressId");

                    b.HasIndex("AttractionName");

                    b.ToTable("Attraction", "supusr", t =>
                        {
                            t.HasCheckConstraint("CK_AttractionNameNotEmpty", "LEN(TRIM(AttractionName)) > 0");
                        });
                });

            modelBuilder.Entity("DbModels.CategoryDbM", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Category", "supusr", t =>
                        {
                            t.HasCheckConstraint("CK_CategoryNameNotEmpty", "LEN(TRIM(CategoryName)) > 0");
                        });
                });

            modelBuilder.Entity("DbModels.CityDbM", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId", "CityName")
                        .IsUnique();

                    b.ToTable("City", "supusr", t =>
                        {
                            t.HasCheckConstraint("CK_CityNameNotEmpty", "LEN(TRIM(CityName)) > 0");
                        });
                });

            modelBuilder.Entity("DbModels.CountryDbM", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("CountryId");

                    b.HasIndex("CountryName")
                        .IsUnique();

                    b.ToTable("Country", "supusr", t =>
                        {
                            t.HasCheckConstraint("CK_CountryNameNotEmpty", "LEN(TRIM(CountryName)) > 0");
                        });
                });

            modelBuilder.Entity("DbModels.CustomerAttractionRatingDbM", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RatingReview")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(200)");

                    b.Property<byte?>("RatingScore")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("RatingTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("CustomerId", "AttractionId");

                    b.HasIndex("AttractionId");

                    b.ToTable("CustomerAttractionRating", "supusr", t =>
                        {
                            t.HasCheckConstraint("CK_RatingHasContent", "(RatingScore IS NOT NULL) OR (RatingReview IS NOT NULL AND LEN(TRIM(RatingReview)) > 0)");

                            t.HasCheckConstraint("CK_RatingScoreRange", "RatingScore BETWEEN 1 AND 5 OR RatingScore IS NULL");
                        });
                });

            modelBuilder.Entity("DbModels.CustomerDbM", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerFirstName")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CustomerLastName")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CustomerUserName")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("CustomerId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CustomerUserName")
                        .IsUnique()
                        .HasFilter("[CustomerUserName] IS NOT NULL");

                    b.ToTable("Customer", "supusr", t =>
                        {
                            t.HasCheckConstraint("CK_CustomerUserNameEmailFormat", "CustomerUserName LIKE '%@%.%'");

                            t.HasCheckConstraint("CK_CustomerUserNameNotEmpty", "LEN(TRIM(CustomerUserName)) > 0");
                        });
                });

            modelBuilder.Entity("DbModels.PostalCodeDbM", b =>
                {
                    b.Property<Guid>("PostalCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCodeNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("PostalCode");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("PostalCodeId");

                    b.HasIndex("CityId", "PostalCodeNumber")
                        .IsUnique();

                    b.ToTable("PostalCode", "supusr", t =>
                        {
                            t.HasCheckConstraint("CK_PostalCodeNotEmpty", "LEN(TRIM(PostalCode)) > 0");
                        });
                });

            modelBuilder.Entity("Models.DTO.AttractionWithoutReviewsDto", b =>
                {
                    b.Property<string>("AttractionDescription")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttractionName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CityName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CountryName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullStreetAddress")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.ToTable((string)null);

                    b.ToView("vw_Attractions_Without_Reviews", "supusr");
                });

            modelBuilder.Entity("Models.DTO.DatabaseOverviewDto", b =>
                {
                    b.Property<int>("NrAttractions")
                        .HasColumnType("int");

                    b.Property<int>("NrCities")
                        .HasColumnType("int");

                    b.Property<int>("NrCustomers")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_Database_Overview", "supusr");
                });

            modelBuilder.Entity("DbModels.AddressDbM", b =>
                {
                    b.HasOne("DbModels.PostalCodeDbM", "PostalCodeDbM")
                        .WithMany("AddressesDbM")
                        .HasForeignKey("PostalCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostalCodeDbM");
                });

            modelBuilder.Entity("DbModels.AttractionCategoryDbM", b =>
                {
                    b.HasOne("DbModels.AttractionDbM", "AttractionDbM")
                        .WithMany("AttractionCategoriesDbM")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModels.CategoryDbM", "CategoryDbM")
                        .WithMany("AttractionCategoriesDbM")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttractionDbM");

                    b.Navigation("CategoryDbM");
                });

            modelBuilder.Entity("DbModels.AttractionDbM", b =>
                {
                    b.HasOne("DbModels.AddressDbM", "AddressDbM")
                        .WithMany("AttractionsDbM")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressDbM");
                });

            modelBuilder.Entity("DbModels.CityDbM", b =>
                {
                    b.HasOne("DbModels.CountryDbM", "CountryDbM")
                        .WithMany("CitiesDbM")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryDbM");
                });

            modelBuilder.Entity("DbModels.CustomerAttractionRatingDbM", b =>
                {
                    b.HasOne("DbModels.AttractionDbM", "AttractionDbM")
                        .WithMany("CustomerAttractionRatingsDbM")
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModels.CustomerDbM", "CustomerDbM")
                        .WithMany("CustomerAttractionRatingsDbM")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttractionDbM");

                    b.Navigation("CustomerDbM");
                });

            modelBuilder.Entity("DbModels.CustomerDbM", b =>
                {
                    b.HasOne("DbModels.AddressDbM", "AddressDbM")
                        .WithMany("CustomersDbM")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AddressDbM");
                });

            modelBuilder.Entity("DbModels.PostalCodeDbM", b =>
                {
                    b.HasOne("DbModels.CityDbM", "CityDbM")
                        .WithMany("PostalCodesDbM")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityDbM");
                });

            modelBuilder.Entity("DbModels.AddressDbM", b =>
                {
                    b.Navigation("AttractionsDbM");

                    b.Navigation("CustomersDbM");
                });

            modelBuilder.Entity("DbModels.AttractionDbM", b =>
                {
                    b.Navigation("AttractionCategoriesDbM");

                    b.Navigation("CustomerAttractionRatingsDbM");
                });

            modelBuilder.Entity("DbModels.CategoryDbM", b =>
                {
                    b.Navigation("AttractionCategoriesDbM");
                });

            modelBuilder.Entity("DbModels.CityDbM", b =>
                {
                    b.Navigation("PostalCodesDbM");
                });

            modelBuilder.Entity("DbModels.CountryDbM", b =>
                {
                    b.Navigation("CitiesDbM");
                });

            modelBuilder.Entity("DbModels.CustomerDbM", b =>
                {
                    b.Navigation("CustomerAttractionRatingsDbM");
                });

            modelBuilder.Entity("DbModels.PostalCodeDbM", b =>
                {
                    b.Navigation("AddressesDbM");
                });
#pragma warning restore 612, 618
        }
    }
}
