<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>AppWebApi</RootNamespace> <!-- The root namespace for the project, ordering numbers in files/folders removed -->
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable> <!-- Values can never be null, unless explicitly allowed -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
      <ProjectReference Include="..\1_Services\1_Services.csproj" />
      <ProjectReference Include="..\3_Models\3_Models.csproj" />
      <ProjectReference Include="..\4_Configuration\4_Configuration.csproj" />
  </ItemGroup>

</Project>
