<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>DbRepos</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\2b_DbContext\2b_DbContext.csproj" />
    <ProjectReference Include="..\2c_DbModels\2c_DbModels.csproj" />
    <ProjectReference Include="..\4_Configuration\4_Configuration.csproj" />
  </ItemGroup>

</Project>
